stages:
  entrenar:
    cmd: python src/train.py
    deps:
      - data/animales       # <--- Antes era data/rps
      - src/train.py
      - src/config.py
    outs:
      - models/modelo_animales.pth  # <--- Nuevo nombre

  convertir:
    cmd: python src/convert.py
    deps:
      - models/modelo_animales.pth
      - src/convert.py
      - src/config.py
    outs:
      - models/modelo_animales.onnx # <--- Nuevo nombre