stages:
  entrenar:
    cmd: python src/train.py
    deps:
      - data/animales
      - src/train.py
      - src/config.py
    outs:
      - models/modelo_animales.pth

  convertir:
    cmd: python src/convert.py
    deps:
      - models/modelo_animales.pth
      - src/convert.py
      - src/config.py
    outs:
      - models/modelo_animales.onnx